service: metadata-scraping
app: metadata-scraping
org: vlence

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: dev
  region: us-east-1
  memorySize: 10240 # chromium runs faster with max memory
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:GetItem
    - dynamodb:PutItem
    Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  getMetadata:
    handler: src/handler.getMetadata
    events:
    - http:
        path: /
        method: post

resources:
  Resources:
    Cache:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cache
        AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        KeySchema:
        - AttributeName: url
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: false
